#!/usr/bin/env python
# coding: utf-8

# In[1]:


import turtle 
turtle.pensize(2) 
for i in range(36):
    for j in range(4): 
        turtle.forward(70) 
        turtle.left(90)
    turtle.left(10)


# In[ ]:
